### ISSUE TITLE
Panic caused by 'index out of bounds: the len is 1 but the index is 1'

### ISSUE THREAD

**Issue by hansonchar** [dacut/scratchstack-aws-signature#2]
In v10.0.x, the line at https://github.com/dacut/scratchstack-aws-signature/blob/0.10.x/base-library/src/signature.rs#L1378 can cause a panic with `'index out of bounds: the len is 1 but the index is 1'`.  The panic occurs when `parts` has length exactly equal to 1:

```rust
        let value = if parts.len() > 0 {
            parts[1]
        } else {
            ""
        };
```

Proposed fix:

```rust
        let value = if parts.len() > 1 {
            parts[1]
        } else {
            ""
        };
```

**Comment by hansonchar** [comment]
This bug is also present in the `main` branch:

  https://github.com/dacut/scratchstack-aws-signature/blob/main/base-library/src/signature.rs#L1303-L1307

**Comment by dacut** [comment]
Thanks, Hanson! Sorry for the delay; was out of Internet range for the better part of last week. Will apply this fix today.

**Comment by hansonchar** [comment]
Hey Dave, hope you enjoyed your time off.  

BTW, in general, you may want to do:
```bash
cargo clippy
```
on your projects.  

Personally I do `cargo check && cargo test && cargo fmt && cargo clipp` routinely before pushing.  I think it helps with many good catches, and would recommend.

**Comment by dacut** [comment]
Alright, this has been fixed. Pushed 0.10.4 to crates.io. Thanks again for the find and fix!

**Comment by hansonchar** [comment]
Thanks, Dave!  

(Minor: You may want to create the tag  `v0.10.4` which seems currently missing on the `0.10.x` branch.)

**Comment by dacut** [comment]
Or, rather, just `git push --tags`, because I forget that `git push` doesn't push tags by default. :-D

**Comment by hansonchar** [comment]
Great!
